export const FETCH_PLAYER = "FETCH_PLAYER"
export const FETCH_PLAYER_DETAIL = 'FETCH_PLAYER_DETAIL'
export const FETCH_CHART_DATA = 'FETCH_CHART_DATA'
export const FETCH_TRIVIAL = 'FETCH_TRIVIAL'
export const SHOW_TRIVIAL_DETAIL = 'SHOW_TRIVIAL_DETAIL'
export const FETCH_PLAYER_COMPARE = 'FETCH_PLAYER_COMPARE'
export const FETCH_USER = 'FETCH_USER';

