export const FETCH_PLAYER = "FETCH_PLAYER"
export const FETCH_PLAYER_DETAIL = 'FETCH_PLAYER_DETAIL'
export const FETCH_CHART_DATA = 'FETCH_CHART_DATA'
export const FETCH_TEAM_LIST = "FETCH_TEAM_LIST"
export const FETCH_TEAM = "FETCH_TEAM"
export const FETCH_TEAM_DETAIL = 'FETCH_TEAM_DETAIL'
export const FETCH_TEAM_PLAYER = 'FETCH_TEAM_PLAYER'