export const TeamUrl = [
    {teamName: "Boston Celtics", url: "http://content.sportslogos.net/logos/6/213/full/slhg02hbef3j1ov4lsnwyol5o.png"},
    {teamName: "Atlanta Hawks", url: "http://content.sportslogos.net/logos/6/220/full/5mdhgjh3aa92kih09pgi.png"},
    {teamName: "Brooklyn Nets", url: "http://content.sportslogos.net/logos/6/3786/full/137_brooklyn-nets-primary-2013.png"},
    {teamName: "Charlotte Hornets", url: "http://content.sportslogos.net/logos/6/5120/full/1926_charlotte__hornets_-primary-2015.png"},
    {teamName: "Chicago Bulls", url: "http://content.sportslogos.net/logos/6/221/full/hj3gmh82w9hffmeh3fjm5h874.png"},
    {teamName: "Cleveland Cavaliers", url: "http://content.sportslogos.net/logos/6/222/full/6921_cleveland_cavaliers-primary-2018.png"},
    {teamName: "Dallas Mavericks", url: "http://content.sportslogos.net/logos/6/228/full/3463_dallas_mavericks-primary-2018.png"},
    {teamName: "Denver Nuggets", url: "http://content.sportslogos.net/logos/6/229/full/xeti0fjbyzmcffue57vz5o1gl.gif"},
    {teamName: "Detroit Pistons", url: "http://content.sportslogos.net/logos/6/223/full/3079.gif"},
    {teamName: "Golden State Warriors", url: "http://content.sportslogos.net/logos/6/235/full/qhhir6fj8zp30f33s7sfb4yw0.png"},
    {teamName: "Houston Rockets", url: "http://content.sportslogos.net/logos/6/230/full/8xe4813lzybfhfl14axgzzqeq.gif"},
    {teamName: "Indiana Pacers", url: "http://content.sportslogos.net/logos/6/224/full/3083.gif"},
    {teamName: "Los Angeles Clippers", url: "http://content.sportslogos.net/logos/6/236/full/bvv028jd1hhr8ee8ii7a0fg4i.png"},
    {teamName: "Los Angeles Lakers", url: "http://content.sportslogos.net/logos/6/237/full/uig7aiht8jnpl1szbi57zzlsh.png"},
    {teamName: "Memphis Grizzlies", url: "http://content.sportslogos.net/logos/6/231/full/793.png"},
    {teamName: "Miami Heat", url: "http://content.sportslogos.net/logos/6/214/full/burm5gh2wvjti3xhei5h16k8e.gif"},
    {teamName: "Milwaukee Bucks", url:"http://content.sportslogos.net/logos/6/225/full/0295onf2c4xsbfsxye6i.png"},
    {teamName: "Minnesota Timberwolves", url:"http://content.sportslogos.net/logos/6/232/full/zq8qkfni1g087f4245egc32po.gif"},
    {teamName: "New Orleans Pelicans", url: "http://content.sportslogos.net/logos/6/4962/full/2681_new_orleans_pelicans-primary-2014.png"},
    {teamName: "New York Knicks", url: "http://content.sportslogos.net/logos/6/216/full/2nn48xofg0hms8k326cqdmuis.gif"},
    {teamName: "Oklahoma City Thunder", url: "http://content.sportslogos.net/logos/6/2687/full/khmovcnezy06c3nm05ccn0oj2.png"},
    {teamName: "Orlando Magic", url: "http://content.sportslogos.net/logos/6/217/full/wd9ic7qafgfb0yxs7tem7n5g4.gif"},
    {teamName: "Philadelphia 76ers", url: "http://content.sportslogos.net/logos/6/218/full/7034_philadelphia_76ers-primary-2016.png"},
    {teamName: "Phoenix Suns", url: "http://content.sportslogos.net/logos/6/238/full/4370_phoenix_suns-primary-2014.png"},
    {teamName: "Portland Trail Blazers", url: "http://content.sportslogos.net/logos/6/239/full/9725_portland_trail_blazers-primary-2018.png"},
    {teamName: "Sacramento Kings", url: "http://content.sportslogos.net/logos/6/240/full/4043_sacramento_kings-primary-2017.png"},
    {teamName: "San Antonio Spurs", url: "http://content.sportslogos.net/logos/6/233/full/2547_san_antonio_spurs-primary-2018.png"},
    {teamName: "Toronto Raptors", url: "http://content.sportslogos.net/logos/6/227/full/4578_toronto_raptors-primary-2016.png"},
    {teamName: "Utah Jazz", url: "http://content.sportslogos.net/logos/6/234/full/6749_utah_jazz-primary-2017.png"},
    {teamName: "Washington Wizards", url: "http://content.sportslogos.net/logos/6/219/full/5671_washington_wizards-primary-2016.png"}
]